"""add google auth, recents, and notification dismissals

Revision ID: aa897d0ab0e2
Revises: 421ad849d4d0
Create Date: 2026-08-29 07:33:38.283640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa897d0ab0e2'
down_revision = '421ad849d4d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recent_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seatgeek_event_id', sa.String(length=50), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('event_date', sa.String(length=50), nullable=True),
    sa.Column('venue_name', sa.String(length=200), nullable=True),
    sa.Column('venue_city', sa.String(length=100), nullable=True),
    sa.Column('event_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('performer_name', sa.String(length=200), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'seatgeek_event_id', name='uq_user_recent_event')
    )
    op.create_table('dismissed_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('saved_event_id', sa.Integer(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['saved_event_id'], ['saved_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'saved_event_id', name='uq_user_dismissed_event')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.create_unique_constraint('uq_users_google_id', ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_google_id', type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('google_id')

    op.drop_table('dismissed_notifications')
    op.drop_table('recent_events')
    # ### end Alembic commands ###
